---
resources:
- name: source-code
  type: git
  source:
    uri: ((github_uri))
    branch: master
    private_key: ((github_key))

- name: cf-deploy
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-organization))
    space: ((cf-space))
    skip_cert_check: false

jobs:
- name: test
  plan:
    - get: source-code
      trigger: true
    - task: test
      file: source-code/ci/task/something-test.yml

- name: deploy
  plan:
    - get: source-code
      passed: [test]
      trigger: true
    - task: build
      file: source-code/ci/task/something-build.yml
    - put: cf-deploy
      params:
        path: build-output/*.jar
        manifest: source-code/cd/manifest.yml

