---
resources:
- name: source-code
  type: git
  source:
    uri: ((github_uri))
    branch: master
    private_key: ((github_key))


jobs:
- name: test
  plan:
    - get: source-code
      trigger: true
    - task: test
      file: source-code/ci/task/something-test.yml

